[azure]
speech_key = "6vmcW5GSB6bFi0KYGces4WlTmyRloPIS8YywkfWBPdIu7P9pswLzJQQJ99ALAC5RqLJXJ3w3AAAYACOGgJAE"
speech_region = "westeurope"
function_url = "auto-service-functions.azurewebsites.net"


[deploy]
subscription_id = "8d2c76a5-8f70-4c62-aebd-b4db1d0c0ee2"
resource_group = "auto-service-functions_group"
webapp_name = "auto-service-dashboard"
